export default {
  DOMAIN: 'http://webservices-v2.crous-mobile.fr:8080/',
  FEEDS: 'feed/feeds.json',
  FEED_AIX: 'feed/aix.marseille/externe/crous-aix.marseille.min.json',
  FEED_AMIENS: 'feed/amiens/externe/crous-amiens.min.json',
  FEED_ANTILLES: 'feed/antilles.guyane/externe/crous-antilles.guyane.min.json',
  FEED_BFC: 'feed/bfc/externe/crous-bfc.min.json',
  FEED_BORDEAUX: 'feed/bordeaux/externe/crous-bordeaux.min.json',
  FEED_CLERMONT:
    'feed/clermont.ferrand/externe/crous-clermont.ferrand.min.json',
  FEED_CORSE: 'feed/corte/externe/crous-corte.min.json',
  FEED_CRETEIL: 'feed/creteil/externe/crous-creteil.min.json',
  FEED_GRENOBLE: 'feed/grenoble/externe/crous-grenoble.min.json',
  FEED_LILLE: 'feed/lille/externe/crous-lille.min.json',
  FEED_LIMOGES: 'feed/limoges/externe/crous-limoges.min.json',
  FEED_LYON: 'feed/lyon/externe/crous-lyon.min.json',
  FEED_MONTPELLIER: 'feed/montpellier/externe/crous-montpellier.min.json',
  FEED_NANCY: 'feed/nancy.metz/externe/crous-nancy.metz.min.json',
  FEED_NANTES: 'feed/nantes/externe/crous-nantes.min.json',
  FEED_NICE: 'feed/nice/externe/crous-nice.min.json',
  FEED_NORMANDIE: 'feed/normandie/externe/crous-normandie.min.json',
  FEED_ORLEANS: 'feed/orleans.tours/externe/crous-orleans.tours.min.json',
  FEED_PARIS: 'feed/paris/externe/crous-paris.min.json',
  FEED_POITIERS: 'feed/poitiers/externe/crous-poitiers.min.json',
  FEED_REIMS: 'feed/reims/externe/crous-reims.min.json',
  FEED_RENNES: 'feed/rennes/externe/crous-rennes.min.json',
  FEED_REUNION: 'feed/reunion/externe/crous-reunion.min.json',
  FEED_STRASBOURG: 'feed/strasbourg/externe/crous-strasbourg.min.json',
  FEED_TOULOUSE: 'feed/toulouse/externe/crous-toulouse.min.json',
  FEED_VERSAILLES: 'feed/versailles/externe/crous-versailles.min.json',
}
