// a bit useless as we only need the keys
export default {
  aix: 'aix-marseille',
  amiens: 'amiens',
  antilles: 'antilles-guyane',
  bfc: 'bfc',
  bordeaux: 'bordeaux',
  clermont: 'clermond-ferrand',
  corse: 'corse',
  creteil: 'creteil',
  grenoble: 'grenoble',
  lille: 'lille',
  limoges: 'limoges',
  lyon: 'lyon',
  montpellier: 'montpellier',
  nancy: 'nancy-metz',
  nantes: 'nantes',
  nice: 'nice',
  normandie: 'normandie',
  orleans: 'orleans-tours',
  paris: 'paris',
  poitiers: 'poitiers',
  reims: 'reims',
  rennes: 'rennes',
  reunion: 'la reunion',
  strasbourg: 'strasbourg',
  toulouse: 'toulouse',
  versailles: 'versailles',
}
